<?xml version="1.0" encoding="utf-8"?><Database Name="team09" Class="RequestDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=co-web;Initial Catalog=team09;User ID=team09" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="team09ConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="team09.Request" Member="Requests">
    <Type Name="Request">
      <Column Name="RequestID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentsRequested" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Week" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Day" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Period" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Semester" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SpecialRequest" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TimeCreated" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DepartmentUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModuleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>